<?php $url          = $this->serverUrl() . $this->url('zfcuser/resetpassword', array('token' => base64_encode($this->token), array('force_canonical' => true))); ?>
<?php $urlcancel    = $this->serverUrl() . $this->url('zfcuser/canceltoken', array('token' => base64_encode($this->token), array('force_canonical' => true))); ?>
<h1>Password Reset</h1>
<p>
    You've forgotten your password and you've requested a password change ? Just clic the link below
</p>
<p>
    <a href="<?php echo $url; ?>"><?php echo $url; ?></a>
</p>
<hr>
<p>
    If you are not the person who requested a password change, please ignore this mail or clic the link below for safety matters
</p>
<p>
    <a href="<?php echo $urlcancel; ?>"><?php echo $urlcancel; ?></a>
</p>